name: build iOS artifact 

on:
  push:
    branches: ["inertia"]

jobs:
  build:
    name: Build and Export IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Archive for iOS Device
        env:
          scheme: ${{ 'Food Truck' }}
        run: |
          xcodebuild clean archive \
              -allowProvisioningUpdates \
              -scheme "Food Truck" \
              -configuration release \
              -archivePath "$PWD/build/Food Truck.xcarchive" \
              -destination "generic/platform=iOS"


      - name: Export IPA
        env:
          scheme: ${{ 'Food Truck' }}
        run: |
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/Food Truck.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$PWD/build/ipa"
            -allowProvisioningUpdates
          
      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.ipa
          path: build/ipa/*.ipa
